In [1]:
import torch 
import numpy as np

# initializing
data = [[1,2],[3,4]]

x_data = torch.tensor(data,dtype=torch.float)

rand_data = torch.rand((2,2))
one_data = torch.ones((2,2))
zero_data = torch.zeros((2,2))

np_to_tensor = torch.from_numpy(np.ones((2,2)))
print(np_to_tensor)


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [2]:
# move tensor from cpu to gpu
print("the doevice of x_data is %s"%x_data.device)
if torch.cuda.is_available():
  x_data = x_data.cuda()
print("the doevice of x_data is %s"%x_data.device)

the doevice of x_data is cpu
the doevice of x_data is cuda:0


In [3]:
# joining tensor
print(torch.cat([one_data,zero_data],dim=1))

tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.]])


In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data,dtype=torch.float)
print(x_data)

# Matrix Multiplication
print(x_data @ x_data.T)
print(x_data.matmul(x_data.T))
print("")

# Element-wise product
print(x_data*x_data)
print(x_data.mul(x_data))

# Single-elenebt tensors
y = x_data.sum()
print(y)
print(type(y))
print(y.item()) # item 함수는 tensor의 value가 하나일 때만 동작 
print(type(y.item()))
print(x_data.tolist()) # value가 여러개일 때는 tolist() 사용

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 5., 11.],
        [11., 25.]])
tensor([[ 5., 11.],
        [11., 25.]])

tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor(10.)
<class 'torch.Tensor'>
10.0
<class 'float'>
[[1.0, 2.0], [3.0, 4.0]]
